#!/home/axel/Python/madmom/env/bin/python
# EASY-INSTALL-DEV-SCRIPT: 'madmom==0.16.dev0','OnsetDetector'
__requires__ = 'madmom==0.16.dev0'
__import__('pkg_resources').require('madmom==0.16.dev0')
__file__ = '/home/axel/Python/madmom/bin/OnsetDetector'
exec(compile(open(__file__).read(), __file__, 'exec'))
